---
dependencies:
- role: geerlingguy.homebrew
  homebrew_installed_packages:
  - tmux
  homebrew_cask_apps:
  - iterm2
  - visual-studio-code
  - jetbrains-toolbox
  when: ansible_distribution == 'MacOSX'
