---
dependencies:
  - role: geerlingguy.homebrew
    homebrew_installed_packages: []
    homebrew_cask_apps:
      - balenaetcher # write images to SD cards
    when: ansible_distribution == 'MacOSX'
