---
- name: git | dotfiles | Remove nonstandard tmux config
  file:
    path: "{{ ansible_env.HOME }}/.gitconfig"
    state: absent

- name: git | dotfiles | Symlink local repo's tmux config
  file:
    src: "{{ role_path }}/files/.gitconfig"
    dest: "{{ ansible_env.HOME }}/.gitconfig"
    state: link
