---
- name: git | dotfiles | Ensure untracked config file exists
  file:
    path: ~/.untracked-gitconfig
    state: touch
    modification_time: preserve
    access_time: preserve

- name: git | dotfiles | Get "stat" of current git config
  stat:
    path: ~/.gitconfig
  register: stat_git_config

- name: git | dotfiles | Remove nonstandard git config
  file:
    path: ~/.gitconfig
    state: absent
  when: stat_git_config.stat.exists and not stat_git_config.stat.islnk

- name: git | dotfiles | Symlink local repo's git config
  file:
    src: "{{ role_path }}/files/.gitconfig"
    dest: ~/.gitconfig
    state: link

- name: Stat for shell additions
  stat:
    path: ~/.git-shellrc
  register: shell_config

- name: Symlink shell config
  file:
    src: "{{ role_path }}/files/.git-shellrc"
    dest: ~/.git-shellrc
    state: link
  when: not shell_config.stat.exists or not shell_config.stat.islnk
