---
# TODO: Set target repo and target dest to variables
# TODO: Ensure vim repo exists as a check to run the
# installation script or not
# - name: Ensure "vimrc" repo exists locally
#   git:
#     repo: https://github.com/amix/vimrc.git
#     dest: ~/.vim_runtime
#     update: no
#   register: already_cloned_check

# - debug: msg="{{ already_cloned_check }}"

- name: Clone "awesome" vim configuration from amix's vimrc repo
  git:
    repo: https://github.com/amix/vimrc.git
    dest: ~/.vim_runtime
    depth: 1

- name: Execute installation script
  shell: sh ~/.vim_runtime/install_awesome_vimrc.sh

- name: Ensure plugin directory exists
  file:
    path: ~/.vim_runtime/sources_non_forked
    state: directory

- name: Apply customizations
  copy:
    src: my_configs.vim
    dest: ~/.vim_runtime/my_configs.vim

# Plugin Installations
- name: Plugins installed to specified pathogen plugin directory
  git:
    repo: "{{ item }}"
    dest: "~/.vim_runtime/sources_non_forked/{{ item.split('/')[3] }}"
  with_items:
    - https://github.com/ekalinin/dockerfile.vim
    - https://github.com/leafgarland/typescript-vim
    - https://github.com/chase/vim-ansible-yaml
    - https://github.com/severin-lemaignan/vim-minimap
    - https://github.com/dsawardekar/wordpress.vim
    - https://github.com/tpope/vim-markdown
    - https://github.com/janko-m/vim-test
    - https://github.com/scrooloose/syntastic
    - https://github.com/ervandew/supertab
    - https://github.com/derekwyatt/vim-scala
    - https://github.com/nathanaelkane/vim-indent-guides

