- name: Playbook to setup local dev machine
  hosts: dev-machine
  roles:
  - developer
  - operations
  - artist
  - arduino-hacker
  - 3d-print-hacker
  - role: macbook
    when: ansible_distribution == 'MacOSX'
